#Note: PLUGIN WILL NOT WORK IF YOU DON'T CONFIGURE THE RANKS.YML ACCORDINGLY TO YOUR SERVER
#PLUGIN 99% WON'T WORK AT YOUR FIRST START SINCE YOU DIDN'T CONFIGURE IT YET
#
#Please check the wiki page to see how you need to configure ranks.yml:
#https://github.com/zorbeytorunoglu/thebestranks/wiki/How-to-use
#
#SQL system is in beta, let me know if you happen to find any bugs.
#Discord Server: https://discord.com/invite/dp3R6A9
sql:
  enabled: false
  host: 'jdbc:mysql://examplehost.com:3306/'
  db-name: 'databaseName'
  username: 'databaseUserName'
  password: 'databaseUserPassword'
  ranks:
    table-name: ranks
    columns:
      uuid: uuid
      rank: rank
chat-format:
  enabled: true
  default-format: '%thebestranks_rank% &r%vault_rankprefix% &f%player_name%&7: &r%message%'
  per-group:
    owner: '%vault_rankprefix% &4%player_name%&7: &r%message%'
    admin: '%vault_rankprefix% &c%player_name%&7: &r%message%'
messages:
  no-perm: '&e&lTBR &7You do not have permission for this'
  only-in-game: '&e&lTBR &7You must be a player to use this command'
  your-rank: '&e&lTBR &7Your rank is %rank%'
  rank-up: '&e&lTBR &7You ranked up from %rank% &7to %next_rank%'
  no-greater-rank: '&e&lTBR &7There is no greater rank than yours, congratulations tiger'
  rank-set-usage: '&e&lTBR &7/rank set &a<player> <rank-id>'
  player-not-found: '&e&lTBR &7Player could not be found'
  rank-doesnt-exists: '&e&lTBR &7There is no rank configured with that ID'
  rank-set: '&e&lTBR &a%player%&7''s rank is set to &a%rank%'
  no-rank-prefix: '&7[&3No Rank&7]'
  no-greater-rank-prefix: '&7No Greater Rank'
  check-rank: '&e&lTBR &a%player%&7''s current rank is &r%rank%'
  unknown-arg: '&e&lTBR &7We could not understand what you want to do. Try &a/rank help'
  status-done: '&a&l✔'
  status-not-done: '&c&l✘'
  reloaded: '&e&lTBR &7All the files are reloaded'
  help-players:
    - '&e&lThe Best Ranks &7- &fEasy and simple rank plugin'
    - ' '
    - '&7/rank &8- &fTo see your current rank'
    - '&7/rank up &8- &fTo rank up if you satisfy all the requirements'
    - '&7/rank help &8- &fTo see this help message'
  help-admin:
    - '&e&lThe Best Ranks &7- &fEasy and simple rank plugin'
    - ' '
    - '&7/rank &8- &fTo see your current rank'
    - '&7/rank up &8- &fTo rank up if you satisfy all the requirements'
    - '&7/rank set &a<player> <rank> &8- &fTo set a rank for a player'
    - '&7/rank help &8- &fTo see this help message'